version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: test
          command: gem install bundler:2.1.4 && bundle install && rake spec